"""Use composite primary key in places table

Revision ID: ff96d1aa88d4
Revises: e932af6045f2
Create Date: 2024-08-15 19:45:16.315772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ff96d1aa88d4'
down_revision: Union[str, None] = 'e932af6045f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_ecosystems() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("places") as batch_op:
        batch_op.drop_constraint("pk_places", type_="primary")
        batch_op.create_primary_key("pk_places", ["engine_uid", "name"])
    # ### end Alembic commands ###


def downgrade_ecosystems() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("places") as batch_op:
        batch_op.drop_constraint("pk_places", type_="primary")
        batch_op.create_primary_key("pk_places", ["id"])
    # ### end Alembic commands ###


def upgrade_app() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_system() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_system() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_archive() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_archive() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

