from .routes.app import *
from .routes.auth import *
from .routes.calendar import *
from .routes.ecosystem import *
from .routes.engine import *
from .routes.hardware import *
from .routes.protected import *
from .routes.sensor import *
from .routes.system import *
from .routes.user import *
from .routes.warning import *
from .routes.weather import *
from .routes.wiki import *
